- name: Create docker network
  become: true
  community.docker.docker_network:
    name: "{{ radarr_bridge_name }}"
    enable_ipv6: yes
    ipam_config:
      - subnet: "{{ radarr_network_ipv6_subnet }}"
    driver_options:
      com.docker.network.bridge.name: "{{ radarr_bridge_name }}"

- name: Create data volume
  become: true
  ansible.builtin.file:
    path: "{{ radarr_vol_base }}"
    mode: 0700
    state: directory
    owner: "{{ radarr_uid }}"
    group: "{{ radarr_gid }}"

- name: Create docker container
  become: true
  community.docker.docker_container:
    name: "{{ radarr_container_name }}"
    image: "{{ radarr_docker_image }}"
    restart_policy: always
    user: "{{ radarr_user }}:{{ radarr_group }}"
    pull: true
    memory: 128M
    networks:
      - name: "{{ radarr_bridge_name }}"
        ipv6_address: "{{ radarr_ipv6_address }}"
    state: started
    cap_drop:
      - all
    volumes:
      - "{{ radarr_vol_base }}:{{ radarr_vol_mount }}"
      - "{{ media_vol_base }}:{{ media_mount_point }}"
