- name: Create mariadb volumes
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: 0700
    state: directory
    owner: "{{ nextcloud_mariadb_vol_uid }}"
    group: "{{ nextcloud_mariadb_vol_gid }}"
  loop:
    - { path: "{{ nextcloud_mariadb_vol_data }}" }
    - { path: "{{ nextcloud_mariadb_vol_dumps }}" }
    - { path: "{{ nextcloud_mariadb_vol_config }}" }
    - { path: "{{ nextcloud_mariadb_vol_backup }}" }

- name: Copy mariadb configuration
  become: true
  ansible.builtin.copy:
    src: 99-custom.cnf
    dest: "{{ nextcloud_mariadb_vol_config }}"
    mode: 0600
    owner: "{{ nextcloud_mariadb_vol_uid }}"
    group: "{{ nextcloud_mariadb_vol_gid }}"

- name: Mariadb container
  become: true
  no_log: true
  community.docker.docker_container:
    name: "{{ nextcloud_mariadb_docker_container }}"
    image: "mariadb:{{ nextcloud_mariadb_version }}"
    user: "{{ nextcloud_mariadb_uid }}:{{ nextcloud_mariadb_gid }}"
    pull: true
    restart_policy: always
    cap_drop:
      - all
    networks:
      - name: "{{ nextcloud_docker_network }}"
        aliases:
          - " {{ nextcloud_mariadb_docker_alias }}"
    state: started
    volumes:
      - "{{ nextcloud_mariadb_vol_data }}:/var/lib/mysql"
      - "{{ nextcloud_mariadb_vol_backup }}:/backup"
      - "{{ nextcloud_mariadb_vol_config }}:/etc/mysql/conf.d/:ro"
      - "{{ nextcloud_mariadb_vol_dumps }}:/docker-entrypoint-initdb.d:ro"
    env:
      MARIADB_ROOT_PASSWORD: "{{ nextcloud_mariadb_root_password }}"

- name: Copy nextcloud backup script
  become: true
  ansible.builtin.template:
    src: nextcloud-backup.sh.j2
    dest: "{{ nextcloud_backup_script }}"
    mode: 0755
      
- name: Copy nextcloud backup systemd timer
  become: true
  register: nextcloudBackupTimer
  ansible.builtin.copy:
    src: nextcloud-backup.timer
    dest: /etc/systemd/system/
    mode: 0644
    directory_mode: 0755
      
- name: Copy nextcloud backup service
  become: true
  register: nextcloudBackupService
  ansible.builtin.template:
    src: nextcloud-backup.service.j2
    dest: /etc/systemd/system/nextcloud-backup.service
    mode: 0644
          
- name: Enable nextcloud backup timer
  become: true
  ansible.builtin.systemd:
    name: nextcloud-backup.timer
    enabled: true
    daemon_reload: "{{ nextcloudBackupTimer.changed or nextcloudBackupService.changed }}"
